services:

  postgres:
    image: postgres:16
    container_name: bm-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:3.9.0
    container_name: bm-kafka
    restart: unless-stopped

    ports:
      - "9094:9094"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@bm-kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://bm-kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    volumes:
      - kafka_data:/var/lib/kafka/data

  bm-auth-service:
    build: ./bm-auth-service
    container_name: bm-auth-service
    restart: unless-stopped

    expose:
      - "8081"

    environment:
      AUTH_DB_URL: ${AUTH_DB_URL}
      AUTH_DB_USERNAME: ${AUTH_DB_USERNAME}
      AUTH_DB_PASSWORD: ${AUTH_DB_PASSWORD}
      AUTH_JWT_SECRET: ${AUTH_JWT_SECRET}
      AUTH_JWT_EXPIRATION_MINUTES: ${AUTH_JWT_EXPIRATION_MINUTES}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}

    depends_on:
      - postgres
      - kafka

  bm-building-service:
    build: ./bm-building-service
    container_name: bm-building-service
    restart: unless-stopped

    expose:
      - "8083"

    environment:
      BUILDING_DB_URL: ${BUILDING_DB_URL}
      BUILDING_DB_USERNAME: ${BUILDING_DB_USERNAME}
      BUILDING_DB_PASSWORD: ${BUILDING_DB_PASSWORD}
      AUTH_SERVICE_URL: http://bm-auth-service:8081

    depends_on:
      - postgres
      - bm-auth-service

  bm-announcement-service:
    build: ./bm-announcement-service
    container_name: bm-announcement-service
    restart: unless-stopped

    expose:
      - "8084"

    environment:
      ANNOUNCEMENT_DB_URL: ${ANNOUNCEMENT_DB_URL}
      ANNOUNCEMENT_DB_USERNAME: ${ANNOUNCEMENT_DB_USERNAME}
      ANNOUNCEMENT_DB_PASSWORD: ${ANNOUNCEMENT_DB_PASSWORD}
      BUILDING_SERVICE_URL: ${BUILDING_SERVICE_URL}

    depends_on:
      - postgres
      - bm-building-service


  bm-audit-service:
    build: ./bm-audit-service
    container_name: bm-audit-service
    restart: unless-stopped

    expose:
      - "8089"

    environment:
      AUDIT_SERVICE_PORT: ${AUDIT_SERVICE_PORT}
      AUDIT_DB_URL: ${AUDIT_DB_URL}
      AUDIT_DB_USERNAME: ${AUDIT_DB_USERNAME}
      AUDIT_DB_PASSWORD: ${AUDIT_DB_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}

    depends_on:
      - postgres
      - kafka

  bm-share-and-help-service:
    build: ./bm-share-and-help-service
    container_name: bm-share-and-help-service
    restart: unless-stopped

    expose:
      - "8085"

    environment:
      SHARE_AND_HELP_DB_URL: ${SHARE_AND_HELP_DB_URL}
      SHARE_AND_HELP_DB_USERNAME: ${SHARE_AND_HELP_DB_USERNAME}
      SHARE_AND_HELP_DB_PASSWORD: ${SHARE_AND_HELP_DB_PASSWORD}
      BUILDING_SERVICE_URL: ${BUILDING_SERVICE_URL}

    depends_on:
      - postgres
      - bm-building-service

  bm-file-service:
    build: ./bm-file-service
    container_name: bm-file-service
    restart: unless-stopped

    expose:
      - "8086"

    environment:
      FILE_SERVICE_PORT: ${FILE_SERVICE_PORT}
      FILE_STORAGE_UPLOAD_DIR: ${FILE_STORAGE_UPLOAD_DIR}

    volumes:
      - ./bm-file-service/uploads:/app/uploads


  bm-chat-service:
    build: ./bm-chat-service
    container_name: bm-chat-service
    restart: unless-stopped

    expose:
      - "8087"

    environment:
      CHAT_SERVICE_PORT: 8087
      CHAT_DB_URL: ${CHAT_DB_URL}
      CHAT_DB_USERNAME: ${CHAT_DB_USERNAME}
      CHAT_DB_PASSWORD: ${CHAT_DB_PASSWORD}
      BUILDING_SERVICE_URL: ${BUILDING_SERVICE_URL}

    depends_on:
      - postgres
      - bm-building-service

  bm-notification-service:
    build: ./bm-notification-service
    container_name: bm-notification-service
    restart: unless-stopped

    expose:
      - "8088"

    environment:
      NOTIFICATION_SERVICE_PORT: ${NOTIFICATION_SERVICE_PORT}
      NOTIFICATION_DB_URL: ${NOTIFICATION_DB_URL}
      NOTIFICATION_DB_USERNAME: ${NOTIFICATION_DB_USERNAME}
      NOTIFICATION_DB_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
      BUILDING_SERVICE_URL: ${BUILDING_SERVICE_URL}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}

    depends_on:
      - postgres
      - bm-building-service
      - kafka


  bm-gateway-service:
    build: ./bm-gateway-service
    container_name: bm-gateway-service
    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
      BUILDING_SERVICE_URL: ${BUILDING_SERVICE_URL}
      ANNOUNCEMENT_SERVICE_URL: ${ANNOUNCEMENT_SERVICE_URL}
      SHARE_AND_HELP_SERVICE_URL: ${SHARE_AND_HELP_SERVICE_URL}
      FILE_SERVICE_URL: ${FILE_SERVICE_URL}
      CHAT_SERVICE_URL: ${CHAT_SERVICE_URL}
      NOTIFICATION_SERVICE_URL: ${NOTIFICATION_SERVICE_URL}
      AUDIT_SERVICE_URL: ${AUDIT_SERVICE_URL}
      AUTH_JWT_SECRET: ${AUTH_JWT_SECRET}

    depends_on:
      - bm-auth-service
      - bm-building-service
      - bm-announcement-service
      - bm-share-and-help-service
      - bm-file-service
      - bm-chat-service
      - bm-notification-service
      - bm-audit-service

volumes:
  postgres_data:
  file_uploads:
  kafka_data: