CREATE DATABASE auth_db;

CREATE DATABASE building_db;

CREATE DATABASE announcement_db;

GRANT ALL PRIVILEGES ON DATABASE auth_db TO bm_user;

GRANT ALL PRIVILEGES ON DATABASE building_db TO bm_user;

GRANT ALL PRIVILEGES ON DATABASE announcement_db TO bm_user;