package com.why.buildingmanagement.audit.domain.model;

public enum AuditEventType {

    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILED,
    USER_REGISTERED,
    PASSWORD_CHANGED,
    PROFILE_UPDATED,

    ANNOUNCEMENT_CREATED,
    ANNOUNCEMENT_UPDATED,
    ANNOUNCEMENT_DELETED,

    POST_CREATED,
    POST_UPDATED,
    POST_DELETED,

    COMMENT_CREATED,
    COMMENT_DELETED,

    CHAT_MESSAGE_CREATED,
    CHAT_MESSAGE_DELETED,

    SYSTEM_EVENT
}