server:
  port: 8080

spring:
  application:
    name: bm-gateway-service

  cloud:
    gateway:
      routes:
        - id: bm-auth-service
          uri: ${AUTH_SERVICE_URL:http://bm-auth-service:8081}
          predicates:
            - Path=/api/auth/**

        - id: bm-building-service
          uri: ${BUILDING_SERVICE_URL:http://bm-building-service:8083}
          predicates:
            - Path=/api/**

security:
  jwt:
    secret: ${AUTH_JWT_SECRET}