server:
  port: 8080

spring:
  application:
    name: bm-gateway-service

  cloud:
    gateway:
      routes:
        - id: bm-auth-service
          uri: ${AUTH_SERVICE_URL:http://bm-auth-service:8081}
          predicates:
            - Path=/api/auth/**

        - id: bm-announcement-service
          uri: ${ANNOUNCEMENT_SERVICE_URL:http://bm-announcement-service:8084}
          predicates:
            - Path=/api/manager/announcements/**,/api/tenant/announcements/**

        - id: bm-building-service
          uri: ${BUILDING_SERVICE_URL:http://bm-building-service:8083}
          predicates:
            - Path=/api/buildings/**,/api/manager/buildings/**,/api/tenant/buildings/**

        - id: bm-share-and-help-service
          uri: ${SHARE_AND_HELP_SERVICE_URL:http://bm-share-and-help-service:8085}
          predicates:
            - Path=/api/manager/share-and-help/**,/api/tenant/share-and-help/**

        - id: bm-file-service
          uri: ${FILE_SERVICE_URL:http://bm-file-service:8086}
          predicates:
            - Path=/api/files/**

        - id: bm-chat-service
          uri: ${CHAT_SERVICE_URL:http://bm-chat-service:8087}
          predicates:
            - Path=/api/tenant/chat/**,/api/manager/chat/**

        - id: chat-websocket
          uri: ${CHAT_SERVICE_URL:http://bm-chat-service:8087}
          predicates:
            - Path=/ws/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials RETAIN_UNIQUE

security:
  jwt:
    secret: ${AUTH_JWT_SECRET}