server:
  port: 8081

spring:
  application:
    name: bm-auth-service

  datasource:
    url: ${AUTH_DB_URL}
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

security:
  jwt:
    secret: ${AUTH_JWT_SECRET}
    expiration-minutes: ${AUTH_JWT_EXPIRATION_MINUTES:60}